# Random Selection

In [1]:
import numpy as np

### 1. Suppose you have a list of numbers and you are asked to select them randomly

#### method 1
Randomize the list and then select sequentially

##### comments

#### method 2
Using an Intermediate list of indices. Randomize the intermediate list but not the original list.
##### comments
using this method keeps the original list unchanged, which comes in handay. Also the efficiency is not reduced.

In [7]:
elements = np.arange(0, 10, 1)
intermediate = np.arange(0, 10, 1)
np.random.shuffle(intermediate)
print(elements)
# print("plane printing")
# for i in intermediate:
#     print(elements[i])
#     pass

print("printing using numpy index facility")
print(elements[intermediate])

[0 1 2 3 4 5 6 7 8 9]
printing using numpy index facility
[8 2 7 4 0 5 3 6 9 1]


### 2. 
Select randomly from a list of elements. Repetition is allowed as long as the selected element is not activated. There is a function that tells if the element should be activated (here it does so randomly). Activated element have nagative value and same magnitude.


#### method

We swap the used value with the unused value of the intermediate list. Swapping is not necessary for algorithm, only assining unused value to used value in the intermediate list is enough. But swapping results in non repeating value in the intermediate list, so that it can be used to display the actual order by which the list was selected.

##### comment
I used this approach in RSBD or Random Sequential Ballistic Deposition for L=1,2 interaction in my MS thesis.

In [35]:
N = 10
elements = np.arange(1, N+1, 1)
intermediate = np.arange(0, N, 1)


In [40]:
def activate_element(elements, i, chan=2):
    """
    elements : list of candidates
    i : index of elements which is a selected candidate for activation
    chan : chance of being activated is 1/chan
    """
    r = np.random.randint(0,chan,1)
    if r == 1:
        # activate
        elements[i] *= -1
        return True
        pass
    return False

In [41]:
forbidden_start_index = 0
while forbidden_start_index < N:
#     print(forbidden_start_index, end=',')
    a = np.random.randint(forbidden_start_index, N, 1)
    b = intermediate[a]
    activated = activate_element(elements, b, 2)
    print(activated, end=',')
    if activated:
        # swapping with used value so that it is not used again
        intermediate[forbidden_start_index], intermediate[a] = intermediate[a], intermediate[forbidden_start_index]
        forbidden_start_index += 1
    

False,True,False,True,True,True,False,True,False,True,False,True,False,True,True,True,

In [42]:
elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
elements[intermediate]

array([ 3,  8,  4,  7,  9, 10,  5,  2,  1,  6])